### ISSUE TITLE
avoid amazon credentials checking

### ISSUE THREAD

**Issue by jackxxu** [jschoch/zdb#3]
i noticed that zdb seems to support local dynamoDB (https://github.com/jschoch/zdb/blob/846c9276ba83e64255cc5fc75fa07b2deadb89a5/config/dev.exs#L5), but I wonder how to avoid credential checking in erlcloud library, to avoid an error message like the following when my local credential is posted to amazon metadata server. 

```
dev
** (EXIT from #PID<0.58.0>) exited in: :gen_server.call(:undefined, {:socket, #PID<0.59.0>, '169.254.169.254', 80, false}, :infinity)
```

**Comment by jschoch** [comment]
It does work with dynamo local...

I think you can just generate a fake set of credentials.  Zdb was an experiment, i'd recommend you look at CargoSense/ex_aws for a "pure" dynamodb api, or my trabant library (also a hack)  if you want some gremlin graph traveral like syntax.
